### ISSUE TITLE
Error on RTR message

### ISSUE THREAD

**Issue by sasensio** [grodansparadis/node-red-contrib-socketcan#21]
Hi,  I have been trying to send an RTR message and no matter how I set it up I get always the same error: "TypeError: Cannot convert undefined or null to object"

![2022-06-10 11_32_57-Window](https://user-images.githubusercontent.com/8171038/173036959-d95649ce-abe8-4a04-9f4d-8f9e9a4b73ce.png)

![2022-06-10 11_32_44-Window](https://user-images.githubusercontent.com/8171038/173036964-36ae4113-c335-4d02-b867-e365d40c19d3.png)

**Comment by grodansparadis** [comment]
Hi,
this actually appears to be a bug. I have fixed it and will upload a ciorrect ed version after lunch.  Thanks for finding this.

**Comment by grodansparadis** [comment]
Version 1.2.7 that fix this problem is available now.

**Comment by sasensio** [comment]
Thanks for the fast update, but the new version force the DLC parameter to 0, there is no rule against using a DLC value different of 0 on a message with RTR enabled.

**Comment by grodansparadis** [comment]
That is the problem with a fast update... :) Yes you are right.  Will fix that.

**Comment by grodansparadis** [comment]
Check 1.2.8 if it does what you want.

**Comment by sasensio** [comment]
Hello, yes is working as expected. 
Thanks for the great job.
