### ISSUE TITLE
Feature Request for socketcan-out node: Allow msg.payload.data to be a Buffer

### ISSUE THREAD

**Issue by nonujigu** [grodansparadis/node-red-contrib-socketcan#23]
Currently, the only supported data type for the CAN frame output in the socketcan-out node is "Array". However, in many scenarios the Buffer type would be more appropriate. Currently, this can only be achieved by modifying the receive.js file in line 97:

original line 97 in receive.js for Array type: `msg.payload.data = Array.prototype.slice.call(frame.data, 0);`

edited line 97 in receive.js for Buffer type: `msg.payload.data = frame.data;`

The advantage of the Buffer type is that you can easily decode the raw data of the can frame with different [read methods from Buffer.js](https://nodejs.org/api/buffer.html#bufreadbigint64beoffset). Another possibility would be to utilize [node-red-contrib-buffer-parser](https://flows.nodered.org/node/node-red-contrib-buffer-parser) to decode the raw data without any function nodes.

A possible solution could be to make the output type (Array/Buffer) configurable within the socketcan-config node.

**Comment by schefa11** [comment]
Good idea,
a very lightweight solution would be just to add another property like "rawData".
E.g.,:
`msg.payload.data = Array.prototype.slice.call(frame.data, 0)`
`msg.payload.rawData = frame.data`

**Comment by grodansparadis** [comment]
Ver 1.2.11 now contains  msg.payload.rawData.  

Thanks!
