### ISSUE TITLE
can out node die afer some time

### ISSUE THREAD

**Issue by MarcinKlima** [grodansparadis/node-red-contrib-socketcan#27]
Hi, got a problem with socketcan-out node, the canout is not sending messages, its freze / died after some time, its run normal after change in node (socketcan-out - flow) and deploy or restart node, work some time and again stop. From terminal see to be work 
property candump etc msg frame incoming Ok. Use to test a virtual VCAN0 (Debian) / node-red 3.0.2 / node v19.3.0 / socketcan latest.
the msg: 
value is the counter++ to from 0 to 255
var msgg = { 
"canfd":false,
"ext": false,
"rtr": false,
"canid": 0x01,
"dlc": 8, 
"data": [value, value, value, value ,value, value,value,value] 
           }
msg.payload = msgg;
return msg;

![can_die](https://user-images.githubusercontent.com/57598271/221970630-f6ba8aed-b01f-441a-b447-15f00f97a497.png)
![can_debug](https://user-images.githubusercontent.com/57598271/221970651-fc21cafa-407d-429d-81af-75e6da0edae3.png)
It just STOP, any idea ? Im have a big problem because want to run in real can interfaces, if its wrong work on virtual, how much percent to work stable on real hardware ? :)

**Comment by grodansparadis** [comment]
Do you get the same problem if you use cangen? Like

cangen vcan0 -g 4 -I 42A -L 8 -D i -v -v

If not on your system it's in the can-utils package

sudo apt install can-utils

That seeme to work here.

Cheers
/Ake

**Comment by MarcinKlima** [comment]
Have 20 years of skill with Linux :) not os problem here, im new in node-red.

ii  can-utils                            2020.11.0-1                                      amd64        SocketCAN userspace utilities and tools

vcan0: flags=193<UP,RUNNING,NOARP>  mtu 72
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 1798250  bytes 14385709 (13.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1798250  bytes 14385709 (13.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


Linux klima.ltd 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

--------

And YES its this same problem, on Linux side, vcan0 packets work property, on node-red socetcan-out frezze after some time, im count this time and a lot of undressing. Worst possible software bug.
![ddie](https://user-images.githubusercontent.com/57598271/222246234-1140f6bd-6d68-4cbc-8a2c-2dc679e89e63.png)
Any Idea ? :D

**Comment by grodansparadis** [comment]
I have no doubt your skills, just want to find a point of failure I can repeat here to. Impossible to find your problem if I can't.  There are hundreds and hundreds of user using this code without problem so the question is what's special on your installation.

Do you get something strange in the node-red log? 

One thing I notices is that you use node 19.3 and node-red support is up to 18.x ([https://nodered.org/docs/faq/node-versions](https://nodered.org/docs/faq/node-versions)). Normally that is not a problem but can be. You can try to downgrade to 18.14.2 stable or similar and see if you get the same problem.

Cheers
/Ake

**Comment by MarcinKlima** [comment]
Downgrade to 18.14.2 don`t help. Must test it on clean install on another device. Very strange.

**Comment by grodansparadis** [comment]
Can you send me the exact flow that fails also so I can run it here. Just in case.

/Ake

**Comment by MarcinKlima** [comment]
Ok, 

[
    {
        "id": "7b24a62e.8f5458",
        "type": "debug",
        "z": "829af3ee.a57c1",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 410,
        "y": 640,
        "wires": []
    },
    {
        "id": "5f671b29.cd24bc",
        "type": "socketcan-out",
        "z": "829af3ee.a57c1",
        "name": "socketcan-out",
        "config": "38e8307.1653f5",
        "x": 150,
        "y": 500,
        "wires": [
            [
                "7b24a62e.8f5458",
                "dab8bea6312dbdee"
            ]
        ]
    },
    {
        "id": "caba412f.047b2",
        "type": "socketcan-in",
        "z": "829af3ee.a57c1",
        "name": "socketcan-out",
        "config": "38e8307.1653f5",
        "x": 360,
        "y": 120,
        "wires": []
    },
    {
        "id": "a64240cb.3f0788",
        "type": "inject",
        "z": "829af3ee.a57c1",
        "name": "Send object - std",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"ext\":false,\"canid\":123,\"dlc\":5,\"data\":[1,2,3,4,5]}",
        "payloadType": "json",
        "x": 160,
        "y": 120,
        "wires": [
            [
                "caba412f.047b2"
            ]
        ]
    },
    {
        "id": "3ff96369.ef6f5c",
        "type": "inject",
        "z": "829af3ee.a57c1",
        "name": "Send string - std",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "123#00112233",
        "payloadType": "str",
        "x": 160,
        "y": 200,
        "wires": [
            [
                "caba412f.047b2"
            ]
        ]
    },
    {
        "id": "6879c00a.5edb68",
        "type": "inject",
        "z": "829af3ee.a57c1",
        "name": "Send string - ext",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "1F334455#1122334455667788",
        "payloadType": "str",
        "x": 160,
        "y": 240,
        "wires": [
            [
                "caba412f.047b2"
            ]
        ]
    },
    {
        "id": "1ee3b274.4cb8fe",
        "type": "inject",
        "z": "829af3ee.a57c1",
        "name": "Send object - ext",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"ext\":true,\"canid\":32278,\"dlc\":5,\"data\":[1,2,3,4,5]}",
        "payloadType": "json",
        "x": 160,
        "y": 160,
        "wires": [
            [
                "caba412f.047b2"
            ]
        ]
    },
    {
        "id": "391a4c45.7acd8c",
        "type": "comment",
        "z": "829af3ee.a57c1",
        "name": "Send CAN frames in using different payloads on VCAN0",
        "info": "",
        "x": 260,
        "y": 80,
        "wires": []
    },
    {
        "id": "912f9928.da2758",
        "type": "comment",
        "z": "829af3ee.a57c1",
        "name": "Receiove CAN data from interface VCAN0",
        "info": "",
        "x": 220,
        "y": 460,
        "wires": []
    },
    {
        "id": "cffe229bb5d7827c",
        "type": "function",
        "z": "829af3ee.a57c1",
        "name": "toCAN",
        "func": "var value = global.get(\"licznik\");\nvalue = value + 1;\nif(value > 255){\n    value = 0;\n}\nglobal.set(\"licznik\", value);\n\nvar msgg = { \n\"canfd\":false,\n\"ext\": false,\n\"rtr\": false,\n\"canid\": 125,\n\"dlc\": 8, \n\"data\": [value, value, value, value ,value, value,value,value] \n           }\n\n\n//msg.payload = JSON.stringify(msgg);\n\nmsg.payload = msgg;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "// Code added here will be run once\n// whenever the node is started.\nglobal.set(\"licznik\", 0);",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 360,
        "wires": [
            [
                "caba412f.047b2",
                "d9b1cad43ad26f3b"
            ]
        ]
    },
    {
        "id": "c203e6489bbe9927",
        "type": "inject",
        "z": "829af3ee.a57c1",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "1",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 130,
        "y": 360,
        "wires": [
            [
                "cffe229bb5d7827c"
            ]
        ]
    },
    {
        "id": "dab8bea6312dbdee",
        "type": "function",
        "z": "829af3ee.a57c1",
        "name": "RECEIVE",
        "func": "\nconst data = msg.payload.data;\nvar id = msg.payload.canid;\n\nvar dane_wynikowe;\n\n//wybranie adresu 123@CAN\nif(id == 125){\n    \n    //czynnosci na danych.s..\n    dane_wynikowe = data[0];\n\n}\n\nmsg.payload = dane_wynikowe;\n\nnode.status({ fill: \"red\", shape: \"dot\", text: dane_wynikowe });\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 560,
        "y": 440,
        "wires": [
            [
                "2bc5ea8a8d4d9c55"
            ]
        ]
    },
    {
        "id": "d9b1cad43ad26f3b",
        "type": "function",
        "z": "829af3ee.a57c1",
        "name": "SEND",
        "func": "\nconst data = msg.payload.data;\nvar id = msg.payload.canid;\n\nvar dane_wynikowe;\n\n//wybranie adresu 123@CAN\nif(id == 125){\n    \n    //czynnosci na danych....\n    dane_wynikowe = data[0];\n\n}\n\nmsg.payload = dane_wynikowe;\n\nnode.status({ fill: \"red\", shape: \"dot\", text: dane_wynikowe });\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 550,
        "y": 360,
        "wires": [
            [
                "7bb584075c0d4da1"
            ]
        ]
    },
    {
        "id": "38e8307.1653f5",
        "type": "socketcan-config",
        "interface": "vcan0"
    }
]

And Im install on clean system on new machine ,  all work fine. To close, problem is on my side, but i don`t know what im must find,last to install on RPI with SPI MCP2515 and run this on real hardware can. Thank You.
