### ISSUE TITLE
Recieve message format wrong

### ISSUE THREAD

**Issue by eddso** [grodansparadis/node-red-contrib-socketcan#4]
Hi,
Node-RED version: v1.0.3
Node.js  version: v10.21.0

The data array output of receive Node does not match what im expect
Documentation for input and output: `"data":[1,2,3,4,5]` 
Real input what i get: `"data":[[1,2,3,4,5]]`

Suggest fix in line: 
https://github.com/grodansparadis/node-red-contrib-socketcan/blob/49dbc73ab62ef84067ed8d849ec71ffdf6f3adfc/src/receive.js#L95
`msg.payload.data = [...frame.data];`

**Comment by grodansparadis** [comment]
Hi thanks,
should be fixed now in 1.0.7  Open again if not.
/Ake
