### ISSUE TITLE
Support for Node-RED 4.0

### ISSUE THREAD

**Issue by schefa11** [grodansparadis/node-red-contrib-socketcan#41]
Package.json contains the dependecy ["node-red": "^3.0.2"].
That leads to another installation of Node-RED inside the node_modules folder. This issue is probably not just related to the new Node-RED (4.x.x) version. I just wondered why the installation takes so much time, so I checked the node_modules folder.

Is there any hard dependency on Node-RED V3? Otherwise I would recommend to remove that from the package.json

**Comment by grodansparadis** [comment]
No, that is an omission from my side.  Changed now.

**Comment by schefa11** [comment]
Thanks for the fast response. When will the update be released?

**Comment by grodansparadis** [comment]
You can test it now
